name: Build and Release
permissions:
    contents: write

on:
    push:
        branches:
            - main
        tags:
            - "*"
env:
    REGISTRY: quay.io
    REPOSITORY: ${{ vars.REPOSITORY }}
    AIB_BASE_IMAGE: ${{ vars.REGISTRY }}/${{ vars.REPOSITORY }}/aib-base-dev
    VERSION: ${{ github.sha }}

jobs:
    build-aib-base-arm64:
        runs-on: ubuntu-24.04-arm
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Quay.io
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.REGISTRY_USER }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Build and push AIB base ARM64
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Containerfile
                  platforms: linux/arm64
                  build-args: |
                      TARGETARCH=arm64
                  push: true
                  provenance: false
                  tags: |
                      ${{ env.AIB_BASE_IMAGE }}:${{ env.VERSION }}-arm64
                      ${{ env.AIB_BASE_IMAGE }}:latest-arm64

    build-aib-base-x86_64:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Quay.io
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.REGISTRY_USER }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Build and push AIB base x86_64
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: Containerfile
                  platforms: linux/amd64
                  build-args: |
                      TARGETARCH=amd64
                  push: true
                  provenance: false
                  tags: |
                      ${{ env.AIB_BASE_IMAGE }}:${{ env.VERSION }}-amd64
                      ${{ env.AIB_BASE_IMAGE }}:latest-amd64

    create-multiarch-manifest:
        needs: [build-aib-base-arm64, build-aib-base-x86_64]
        runs-on: ubuntu-24.04
        steps:
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Quay.io
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ secrets.REGISTRY_USER }}
                  password: ${{ secrets.REGISTRY_PASSWORD }}

            - name: Create and push multi-architecture images
              run: |
                  docker buildx imagetools create \
                    -t ${{ env.AIB_BASE_IMAGE }}:${{ env.VERSION }} \
                    ${{ env.AIB_BASE_IMAGE }}:${{ env.VERSION }}-arm64 \
                    ${{ env.AIB_BASE_IMAGE }}:${{ env.VERSION }}-amd64

                  docker buildx imagetools create \
                    -t ${{ env.AIB_BASE_IMAGE }}:latest \
                    ${{ env.AIB_BASE_IMAGE }}:latest-arm64 \
                    ${{ env.AIB_BASE_IMAGE }}:latest-amd64
